apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-lb8bd
  creationTimestamp: "2020-04-17T11:07:50Z"
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-xlr-consul
  name: consul
  namespace: xlr
  resourceVersion: "16427794"
  selfLink: /apis/apps/v1/namespaces/xlr/deployments/consul
  uid: a02b8cc3-1d99-4f82-98d3-086edc95dbe0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-xlr-consul
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-04-17T11:07:49Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-xlr-consul
    spec:
      containers:
      - image: bitnami/consul:latest
        imagePullPolicy: IfNotPresent
        name: consul
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /bitnami
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/nfs/xebialabs/slack-bot/data/consul
          type: ""
        name: vol1
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-17T11:07:57Z"
    lastUpdateTime: "2020-04-17T11:07:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-17T11:07:50Z"
    lastUpdateTime: "2020-04-17T11:07:57Z"
    message: ReplicaSet "consul-79489b4c76" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
